language: python
python:
    - 2.7
    - 3.4
before_install:
    - sudo apt-get update
    - sudo apt-get install gfortran libopenblas-dev liblapack-dev
install: 
    - python setup.py install
script: 
    - python main.py
